### ISSUE TITLE
Unity 2022.2 Fails to serialize objects to json properly

### ISSUE THREAD

**Issue by fernanbg** [RageAgainstThePixel/com.rest.elevenlabs#17]
# Bug Report
```
2023/05/25 12:16:36.835 9596 9634 Error Unity JsonSerializationException: Unable to find a constructor to use for type ElevenLabs.Voices.Sample. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'samples[0].sample_id', line 1, position 78.
2023/05/25 12:16:36.835 9596 9634 Error Unity   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject (Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonObjectContract objectContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, Newtonsoft.Json.Serialization.JsonProperty containerProperty, System.String id, System.Boolean& createdFromNonDefaultCreator) [0x00000] in <00000000000000000000000000000000>:0 
2023/05/25 12:16:36.835 9596 9634 Error Unity   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, New
```

## Overview
Execution Error when  call  `api.VoicesEndpoint.GetVoiceAsync(IdElevenLabs)` which Unity 2022.2.20

## To Reproduce
1. Create a new project in Unity 2022.2.20
2. Configure for Android with I2CPP
3. Add this pakage
4. Put the api key
5. Put a script with this in the start method:
```csharp
        ElevenLabsClient api = new ElevenLabsClient();
        Voice voice = (await api.VoicesEndpoint.GetVoiceAsync(IdVoiceElevenLabs));
```
6. Buid & Run and it woks OK with no error
7. Add URP Pakage and configure Graphics in Player settings to use it
8. Build & Run and produce an error when execure GetVoiceAsync

## Expected behavior
No error and recive a correct voice return 

In Unity  2021.3.24f1 works good with no error

**Comment by StephenHodgson** [comment]
@fernanbg what should `IdVoiceElevenLabs` be set as?

**Comment by StephenHodgson** [comment]
So the error only crops up when URP is installed?

**Comment by StephenHodgson** [comment]
@fernanbg seems to be a bug with Unity 🤔 

I tested with 2021.3 LTS and it seems okay. 
When I test with 2022.2 the json serialization seems to always return an empty json string.

**Comment by StephenHodgson** [comment]
@fernanbg try updating the newtonsoft package 3.2.1

**Comment by StephenHodgson** [comment]
Hmm updating to 3.2.1 didn't help either.
I also tried changing from .net standard to .net framework still same results

**Comment by fernanbg** [comment]
I have found that perhaps it is a problem with IL2CCP in Android and the UnityLinker's bytecode stripping.  But I don´t know what happens only when I put URP in the project, and with the 2022.2 Unity version.
https://github.com/jilleJr/Newtonsoft.Json-for-Unity/wiki/Fix-AOT-using-link.xml

**Comment by StephenHodgson** [comment]
It's failing for me even without URP

**Comment by StephenHodgson** [comment]
That's a great link for the Newton soft stuff but I've already mitigated the problem using the following:

https://github.com/RageAgainstThePixel/com.rest.elevenlabs/blob/08ab1489438e55004a26445614b97a4dfd465b01/ElevenLabs/Packages/com.rest.elevenlabs/Runtime/AssemblyInfo.cs#L7

**Comment by StephenHodgson** [comment]
Also we're using unity's Newton soft package directly

**Comment by StephenHodgson** [comment]
@fernanbg I just tried with 2022.2 LTS and it worked when I changed `Managed Stripping Level` down to `Minimal`. 

Crazy cuz I have both the link.xml and the preserve and link assembly attributes in there and it is _still_ getting stripped from the build. Crazy.
