### ISSUE TITLE
Getting voices in WebGL builds cause an error

### ISSUE THREAD

**Issue by lucasfaesa** [RageAgainstThePixel/com.rest.elevenlabs#18]
# Bug Report

## Overview
When trying to get the available voices in WebGL, it returns the following error on build:
"DllNotFoundException: Unable to load DLL 'libc'."
Maybe this happens with other calls as well, but since "GetAllVoicesAsync" is the first one, I can't tell.

## To Reproduce
1. Build to WebGL using Unity 2021.3.25f
2. Wait for the call
3. Get the error

If it doesn't work on Web I'm sorry, tried searching on the ReadMe, but didn't found.

**Comment by StephenHodgson** [comment]
Web GL is not supported for this package.

**Comment by StephenHodgson** [comment]
your best bet is to make an actual webapp

**Comment by StephenHodgson** [comment]
Unity doesn't support theading for webGL builds yet.

**Comment by lucasfaesa** [comment]
Oh, Ok! Thanks man!

**Comment by StephenHodgson** [comment]
No worries! Sorry, hopefully they will support it soon when they move to .net 7

I did have some tasks planned to better support the async/await in webGL builds but I had to put it on hold.
https://github.com/RageAgainstThePixel/com.utilities.async/issues/2
