### ISSUE TITLE
Audio Streaming

### ISSUE THREAD

**Issue by chrisecoleman** [RageAgainstThePixel/com.rest.elevenlabs#28]
# Feature Request

## Is your feature request related to a problem? Please describe.
Yes, i want to reinforce the need for streaming support.  I am encountering the mentioned instabilities in Stream Text to Speech

## Describe the solution you'd like
Unity support for Stream Text to Speech

## Describe alternatives you've considered
currently i am loading the full audio and its a very long delay for multi-page text.

## Additional context
I realize this may be out of your control, but alternative solutions would be appreciated, is Unity aware of and tracking this bug?

**Comment by StephenHodgson** [comment]
Never got an update after submitting repro examples

https://forum.unity.com/threads/downloadhandleraudioclip-streamaudio-is-ignored.699908/#post-9127066

**Comment by StephenHodgson** [comment]
I also discussed the same problem to the eleven labs team and proposed changes to the API to enable streaming of the raw pcm data but they didn't want to make the requred changes.

**Comment by StephenHodgson** [comment]
My only suggestion is to maybe break up the text into smaller segments and submit in chunks

**Comment by chrisecoleman** [comment]
thanks for the reply, and the suggestion!
