### ISSUE TITLE
Stream Text to Speech

### ISSUE THREAD

**Issue by SebastianBlandon** [RageAgainstThePixel/com.rest.elevenlabs#37]
In the new version (3.0.1), the downloaded voice is reproduced as the voice of a squirrel.

**Comment by StephenHodgson** [comment]
There isn't enough information in your description to understand the problem

**Comment by StephenHodgson** [comment]
Please open a new ticket and properly fill out required information

**Comment by StephenHodgson** [comment]
may be related to #35
