### ISSUE TITLE
Question about api integration with Unity Projects

### ISSUE THREAD

**Issue by braxtontalbert** [RageAgainstThePixel/com.rest.elevenlabs#39]
Hey team, I have a question regarding api integration in project files.
I am using Rider and trying to access the api for a Unity project that is targeting framework 4.7.2. As far as I know Unity only supports up to target framework 4.x, so I am confused on how to integrate this into my Rider project. I have tried installing via Nuget, but it seems to require framework 6, which is not supported for the project that I am implementing this with. Any help would be appreciated!

**Comment by StephenHodgson** [comment]
See https://github.com/RageAgainstThePixel/com.rest.elevenlabs#via-unity-package-manager-and-openupm

**Comment by StephenHodgson** [comment]
The nuget package is not meant to be used with Unity engine, but this package is specifically designed for it.
