### ISSUE TITLE
Plugin fails deserializing voices

### ISSUE THREAD

**Issue by tomkail** [RageAgainstThePixel/com.rest.elevenlabs#40]
Hello! I'm on the latest package.

When the inspector is looking at the Eleven Labs Configuration file or trying to load voices in the Dashboard, it repeatedly throws the error:
`Newtonsoft.Json.JsonSerializationException: A member with the name 'name' already exists on 'ElevenLabs.Voices.Voice'. Use the JsonPropertyAttribute to specify another name.`

<img width="824" alt="image" src="https://github.com/RageAgainstThePixel/com.rest.elevenlabs/assets/1252816/536245df-63df-4f47-b780-74d1acedc4ee">

**Comment by StephenHodgson** [comment]
Interesting, I didn't change too much with voices

🤔

**Comment by tomkail** [comment]
I've just fixed it by adding an underscore to the "name" backing field.
I think the issue is that JSON.Net has been told to serialize the json property "name" into the property "Name", but because there's a field explicitly called "name" it's unsure which to write the json data into.

Same issue exists in VoiceSettings on stability and style.

<img width="385" alt="image" src="https://github.com/RageAgainstThePixel/com.rest.elevenlabs/assets/1252816/a6bae431-bda9-4719-964d-548ad35732a2">

**Comment by StephenHodgson** [comment]
It sounds like they changed something with the API itself.

Last time I ran this it wasn't a problem

**Comment by StephenHodgson** [comment]
I don't use underscore prefixes in member names, we ill probably come up with something else.

But I would also like an example to try and repro.

**Comment by StephenHodgson** [comment]
Did you somehow change the json serialization settings? 

Bc the fields should be ignored by default

**Comment by tomkail** [comment]
I haven't changed the json serialization settings used by the package, but it's possible our app replaces the default settings? I don't believe that would matter though, since you use ElevenLabsClient.JsonSerializationOptions on DeserializeObject

**Comment by StephenHodgson** [comment]
Hmm interesting bc I have not changed the implementation details of this class in almost 8 months, except for adding the name parameter to the constructor.

**Comment by tomkail** [comment]
Ahh I've got it. This plugin adds a contract that serializes private types, even if marked with JsonIgnore.
https://github.com/applejag/Newtonsoft.Json-for-Unity.Converters
