### ISSUE TITLE
<_UIKBFeedbackGenerator: 0x28240bd00>: Couldn't update haptics muting for dictation audio recording. No engine.

### ISSUE THREAD

**Issue by yosun** [RageAgainstThePixel/com.rest.elevenlabs#42]
# Bug Report

## Overview
when dictation on keyboard is attempted this occurs  
<_UIKBFeedbackGenerator: 0x28240bd00>: Couldn't update haptics muting for dictation audio recording. No engine.

## To Reproduce
1. Build to iOS device
2. try to input text using the mic for dictation
3. notice the static

## Expected behavior
the static should not sound
should not see this in xcode

**Comment by StephenHodgson** [comment]
I still do not understand what the problem is.

I need better logging or stack traces that show the source of the problem being of this library.

**Comment by yosun** [comment]
0. import package
1. With the Unity UI Input Field on iOS device, use the voice dictation as input 
2. Notice the static

**Comment by StephenHodgson** [comment]
Have you tried without my package?

I don't think my package has anything to do with dictation
