### ISSUE TITLE
Arabic Encoding

### ISSUE THREAD

**Issue by aynader** [RageAgainstThePixel/com.rest.elevenlabs#47]
It appears that the API doesn't encode Arabic correctly, Arabic text generated through the API is 'distorted' while Arabic text generated on the website, works as intended.

**Comment by StephenHodgson** [comment]
@aynader can you provide me with some example text please?

**Comment by aynader** [comment]
sure!

"أنا مش عارفني، أنا تهت مني، أنا مش أنا"

"لا دي ملامحي ولا شكلي، شكلي ولا دا أنا"

"أبص لروحي فجأة لقيتني"

"لقيتني كبرت، فجأة كبرت"

"تعبت من المفاجأة ونزلت دمعتي"

"قولي لي إيه يا مرايتي"

"قولي لي إيه حكايتي تكونشي"

"تكونشي دي نهايتي، وآخر قصتي"

**Comment by aynader** [comment]
I just figured it out.
You just need to update this:
`var request = new TextToSpeechRequest(text, model, defaultVoiceSettings);`

to:

`string encodedText = Encoding.UTF8.GetString(utf8Bytes);
var request = new TextToSpeechRequest(encodedText, model, defaultVoiceSettings);`

I tested it and it works flawlessly.

**Comment by StephenHodgson** [comment]
I wouldn't necessarily consider this a bug with the library itself, but good to know that text may need to be reencoded before sending.

**Comment by StephenHodgson** [comment]
I'll keep this open a bit longer as I do more research on what to do for next steps.

**Comment by StephenHodgson** [comment]
Latest version gives you more power to specify encoding if needed. Tested this out and seemed to work ok, but would like validation with native speaker.
