### ISSUE TITLE
Get Key from %APPDATA% instead

### ISSUE THREAD

**Issue by omfgitzneo** [RageAgainstThePixel/com.rest.elevenlabs#6]
# Feature Request
Is there a way for us to get the ElevenLabs key from %APPDATA% .json file instead?

## Is your feature request related to a problem? Please describe.

I would want to be able to ship my Unity Game to other users so I would like to at least stop unwanted users from abusing my key.

## Describe the solution you'd like

Creating a way (Or teaching me how to if it's available right now) to retrieve keys from a .json file

**Comment by StephenHodgson** [comment]
You actually can setup a json file named `.elevenlabs` and it will read your api key that way. 

https://github.com/RageAgainstThePixel/com.rest.elevenlabs/blob/48e1fcf42d5586dc556cbcee883fd5c2670d7822/ElevenLabs/Packages/com.rest.elevenlabs/Runtime/ElevenLabsAuthentication.cs#L99

**Comment by StephenHodgson** [comment]
You'd use it like this: 

```
var auth = ElevenLabsAuthentication.LoadFromDirectory("path/to/your/directory", "yourFileName");
var client = new ElevenLabsClient(auth);
```

**Comment by StephenHodgson** [comment]
But your problem will still be there as anyone can sniff your api calls with wire shark, as the auth is passed in the headers.

Again your best bet is to setup an API proxy.

**Comment by StephenHodgson** [comment]
Honestly tho, this api is pretty expensive thb, your best bet to generate everything you need in editor ahead of time for now. I'll work on the proxy API support when I get a chance.
