### ISSUE TITLE
There should be an option to disable audioClip caching

### ISSUE THREAD

**Issue by StephenHodgson** [RageAgainstThePixel/com.rest.elevenlabs#85]
Option to disable caching when requesting TextToSpeech audio clip should be possible.

**Comment by ChebanovDD** [comment]
Hi there, is there any ETA for this one? Thanks 🙂

**Comment by StephenHodgson** [comment]
I can make it a higher priority, this is blocking full WebGL build support as well.

**Comment by yosun** [comment]
any update? been like 6+months

**Comment by StephenHodgson** [comment]
This is already closed and completed
